---
ID: "0f30dac6-ff7b-4545-ba3e-01a2c8f83212"
Parent: "ead2d166-f685-43a4-bb86-6d23bafb457c"
Template: "2e1d7985-0bf1-469b-a00b-4f2ac443940c"
Path: /sitecore/content/ironthrone/health/Presentation/Rendering Variants/JSON List/Default
DB: master
BranchID: "08c12327-7685-4c17-bfca-6aae7a55f4c5"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{6E634FCA-8F4D-43E1-ADDD-5A26706605DF}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191127T080141Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
